routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

//Halaman home
Route::get('/', 'HomeCOntroller@index');

//Halaman admin
Route::resource('blog', 'admin\BlogController')->middleware(['auth', 'admin']);
Route::resource('category', 'admin\CategoryController')->middleware(['auth', 'admin']);
Route::get('profile', 'admin\ProfileController@index')->middleware(['auth', 'admin'])->name('profile');
Route::post('profile/update', 'admin\ProfileController@update')->middleware(['auth', 'admin']);
Auth::routes();
Route::get('blogs/{id}', 'HomeController@show');
Route::get('/home', 'HomeController@index')->name('home');
// post comment
Route::post('comment', 'CommentController@store');

resources/views/admin/pages/blog.blade.php
@extends('admin.master')
@push('css')
<link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush
@section('pages','Blog')
@section('content')
<div class="card">
  <div class="card-header"><a href="{{route('blog.create')}}" class="btn btn-primary">New Blog</a></div>
  <div class="card-body">
      <table class="table table-bordered datatables">
        <thead>                  
          <tr>
            <th style="width: 10px">#</th>
            <th>Category</th>
            <th>Author</th>
            <th>Title</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
     {{-- @forelse ($blog as $index=>$blogs)
     <tr>
      <td>{{ $index + 1 }}</td>
      <td>{{$blogs->categories->name}}</td>
      <td>{{ $blogs->users->name}}</td>
      <td>{{ $blogs->title }}</td>
      <td>
          <form action="{{ route('blog.destroy', $blogs->id) }}" method="POST">
              @csrf
              @method('delete')
              <a href="{{route('blog.edit',$blogs->id)}}" style="margin-right: 20px"><i
                      class="fas fa-edit"></i></a>
              <button style="border: none;
                      background: none;
                      "><i class="fas fa-trash"></i></button>
          </form>
      </td>
  </tr>
     @empty
         <tr> <td class="text-center" style="background-color:rgba(221, 221, 221, 0.644);" colspan="3"><h3>No Data</h3></td></tr>
     @endforelse --}}
        </tbody>
      </table>
    </div>
</div>
@endsection
@push('script')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script type="text/javascript">
  $(function () {
    $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
    });
    var table = $('.datatables').DataTable({
        processing: false,
        serverSide: true,
        ajax: "{{ route('blog.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'categories.name', name: 'categories'},
            {data:'users.name',name:'author'},
            {data: 'title', name: 'title'},
            {
                data: 'action', 
                name: 'action', 
                orderable: true, 
                searchable: true
            },
        ]
    });
    $('body').on('click','.delete',function(){
      var blog_id = $(this).data('id');
      Swal.fire({
      title: 'Are you sure?',
      text: "You won't be able to revert this!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, delete it!'
    }).then((result) => {
      if (result.isConfirmed) {
      $.ajax({
            type: "DELETE",
            url: "/blog/"+blog_id,
            success: function (data) {
                table.draw();
                Swal.fire(
              'Deleted!',
              'Your blog has been deleted.',
              'success'
            )
            },
            error: function (data) {
                console.log('Error:', data);
            }
        });
      
  
       }
})
    });
// $.get( "{{route('blog.index')}}", function( data ) {
//   console.log(data);;
//   alert( "Load was performed." );
// });
  });
</script>
@endpush

resources/views/admin/pages/category.blade.php
@extends('admin.master')
@section('pages','Category')
@section('content')
<div class="card">
    <div class="card-header"><button class="btn btn-primary" data-toggle="modal" data-target="#createmodal">New Category</button></div>
    <div class="card-body">
        <table class="table table-bordered">
          <thead>                  
            <tr>
              <th style="width: 10px">#</th>
              <th>Name</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
       @forelse ($category as $index=>$categories)
       <tr>
        <td>{{ $index + 1 }}</td>
        <td>{{ $categories->name }}</td>
        <td>
            <form action="{{ route('category.destroy', $categories->id) }}" method="POST">
                @csrf
                @method('delete')
                <a href="javascript:;" id="edit_btn" data-id="{{ $categories->id }}"
                    data-name="{{ $categories->name }}" style="margin-right: 20px"><i
                        class="fas fa-edit"></i></a>
                <button style="border: none;
                        background: none;
                        "><i class="fas fa-trash"></i></button>
            </form>
        </td>
    </tr>
       @empty
           <tr> <td class="text-center" style="background-color:rgba(221, 221, 221, 0.644);" colspan="3"><h3>No Data</h3></td></tr>
       @endforelse
          </tbody>
        </table>
      </div>
</div>
{{-- modal --}}
<div class="modal fade" id="createmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form action="{{ route('category.store') }}" method="post">
            @csrf  
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <div class="form-group">
                <label for="name">Name Category</label>
                <input type="text" name="name_category" class="form-control"
                    placeholder="Insert Category Name...">
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Add Category</button>
        </div>
    </form>
      </div>
    </div>
  </div>
  {{-- modal edit --}}
  <div class="modal fade" id="editmodal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <form action="{{ route('category.store') }}" method="post">
        @csrf
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit Categories</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <input type="hidden" name="id" id="id">
                        <label for="name">Name Categories</label>
                        <input type="text" name="name_category" id="name_categories" class="form-control" value="">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
    </form>
</div>
</div>
@endsection
@push('script')
    <script>
        $(document).ready(function() {
            $("table #edit_btn").click(function() {
                var id = $(this).data('id');
                var name = $(this).data('name');
                $('#editmodal').modal('show');
                $('#id').val(id);
                $('#name_categories').val(name);
            })
        });

    </script>
@endpush

resources/views/admin/pages/create_blog.blade.php
@extends('admin.master')
@push('css')
<link rel="stylesheet" href="{{ asset('admin')}}/plugins/summernote/summernote-bs4.css">
@endpush
@section('pages','Create Blog')
@section('content')
<div class="col-md-12">
    <div class="card card-outline card-info">
      <div class="card-header">
        <h3 class="card-title">
          Create New Blog
        </h3>
      </div>
      <!-- /.card-header -->
      <div class="card-body pad">
        <form action="{{route('blog.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
          <label for="exampleFormControlInput1">Title</label>
          <input type="text" class="form-control" name="title" placeholder="Insert Blog Title...">
        </div>
        <div class="form-group">
          <label for="exampleFormControlSelect1">Category</label>
          <select class="form-control" name="categories" >
            <option>--Select Category--</option>
            @foreach ($category as $categories)
            <option value="{{$categories->id}}">{{$categories->name}}</option>
            @endforeach
          </select>
        </div>
        <div class="mb-3">
          <label>Content</label>
          <textarea class="textarea" placeholder="Place some text here" name="content"></textarea>
        </div>
        <div class="form-group mb-3">
          <label>Photo</label>
            <input type="file" name="photo" class="form-control" id="inputGroupFile01">
          </div>
        </div>
        <div class="form-group px-2 py-3">
          <input type="submit" value="Save" class="btn btn-primary float-right">
        </div>
      </form>
      </div>
    </div>
  </div>

  <!-- /.col-->
@endsection
@push('script')
<script src="{{asset('admin')}}/plugins/summernote/summernote-bs4.min.js"></script>
<script>
    $(function () {
      // Summernote
      $('.textarea').summernote()
    })
  </script>
@endpush

resources/views/admin/pages/edit_blog.blade.php
@extends('admin.master')
@push('css')
<link rel="stylesheet" href="{{ asset('admin')}}/plugins/summernote/summernote-bs4.css">
@endpush
@section('pages','Edit Blog')
@section('content')
<div class="col-md-12">
  <div class="card card-outline card-info">
    <div class="card-header">
      <h3 class="card-title">
        Create New Blog
      </h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body pad">
      <form action="/blog/{{$blog->id}}" method="post" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
          <label for="exampleFormControlInput1">Title</label>
          <input type="text" class="form-control" name="title" value="{{$blog->title}}" placeholder="Insert Blog Title...">
        </div>
        <div class="form-group">
          <label for="exampleFormControlSelect1">Category</label>
          <select class="form-control" name="categories">
            <option>--Select Category--</option>
            @foreach ($category as $categories)
            <option value="{{$categories->id}}" {{($categories->id == $blog->categories_id) ? 'selected':''}}>{{$categories->name}}</option>
            @endforeach
          </select>
        </div>
        <div class="mb-3">
          <label>Content</label>
          <textarea class="textarea" placeholder="Place some text here"  name="content">{{$blog->content}}</textarea>
        </div>
        <div class="form-group mb-3">
          <label>Photo</label>
          <input type="file" name="photo" class="form-control" id="inputGroupFile01">
        </div>
    </div>
    <div class="form-group px-2 py-3">
      <input type="submit" value="Save" class="btn btn-primary float-right">
    </div>
    </form>
  </div>
</div>
</div>

<!-- /.col-->
@endsection
@push('script')
<script src="{{asset('admin')}}/plugins/summernote/summernote-bs4.min.js"></script>
<script>
  $(function() {
    // Summernote
    $('.textarea').summernote()
  })
</script>
@endpush

resources/views/admin/pages/profile.blade.php
@extends('admin.master')
@section('pages','Profile')
@section('content')
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Profile</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="/profile/update" method="POST">
        @csrf
          <div class="card-body">
            <div class="form-group">
                <label>Name</label>
                <input type="text" class="form-control" name="name" value="{{$profile->name}}" placeholder="Enter Name">
              </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" name="email" value="{{$profile->email}}" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">New Password</label>
              <input type="password" class="form-control" name="password" placeholder="Password">
            </div>
          </div>
          <!-- /.card-body -->
          <div class="card-footer">
            <button type="submit" class="btn btn-primary float-right">Save</button>
          </div>
        </form>
      </div>
      <!-- /.card -->
@endsection