routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

//Halaman home
Route::get('/', 'HomeCOntroller@index');

//Halaman admin
Route::resource('blog', 'admin\BlogController')->middleware(['auth', 'admin']);
Route::resource('category', 'admin\CategoryController')->middleware(['auth', 'admin']);
Route::get('profile', 'admin\ProfileController@index')->middleware(['auth', 'admin'])->name('profile');
Route::post('profile/update', 'admin\ProfileController@update')->middleware(['auth', 'admin']);
Auth::routes();
Route::get('blogs/{id}', 'HomeController@show');
Route::get('/home', 'HomeController@index')->name('home');
// post comment
Route::post('comment', 'CommentController@store');

resources/views/admin/layout/navbar.blade.php
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/" class="nav-link">Home</a>
      </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <button class="btn btn-danger">Logout</button>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

resources/views/admin/layout/sidebar.blade.php
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <h3 class="px-3">Kucingku</h3>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          {{-- <img src="{{asset('admin')}}/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image"> --}}
          <a href="#"><i class="fas fa-user fa-lg"></i></a>
        </div>
        <div class="info">
          <a href="#" class="d-block">{{Auth::user()->name}}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
               <li class="nav-item">
                <a href="{{route('profile')}}" class="nav-link">
                  <i class="nav-icon fas fa-user"></i>
                  <p>
                    Profile
                  </p>
                </a>
              </li>
          <li class="nav-item">
            <a href="{{route('blog.index')}}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Blog
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('category.index')}}" class="nav-link">
              <i class="nav-icon fas fa-list-ul"></i>
              <p>
                Category
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>